<?php /* @var $block \Magento\Framework\View\Element\Template */ ?>
<div class="field gift-wrap">
    <label class="label" for="">
        <span><?= __('Gift Wrap'); ?></span>
    </label>
    <div class="control">
        <input type="checkbox" name="gift-wrap" value="1" id="gift-wrap">
        <label class="label admin__field-label" for="gift-wrap">
            <span class="price-notice">+
                <span class="price-container">
                    <span data-price-amount="1" data-price-type="" class="price-wrapper">$1.00</span>
                </span>
            </span>
        </label>
    </div>
</div>
